export const Phases = {
	START: 'START',
	STEP_SELECTING: 'STEP_SELECTING',
	FORM_FILING: 'FORM_FILING',
	SUCCESS: 'SUCCESS',
};

export const Steps = {
	PERSONAL_DETAILS: 'PERSONAL_DETAILS',
	ADDITIONAL_INFORMATION: 'ADDITIONAL_INFORMATION',
	ADDITIONAL_FILES: 'ADDITIONAL_FILES',
};
